### ISSUE TITLE
There is no extension able to load the configuration for "log_files"

### ISSUE THREAD

**Issue by GJoffrey** [evotodi/log-viewer-bundle#1]
Hello !

Your project is very interesting ! But when I try to use it, i got an error :

`There is no extension able to load the configuration for "log_files" (in C:\Path\to\the\config\files\config/packages/evo_log_viewer.yaml). Looked for namespace "log_files", found "framework", "sensio_framework_extra", "doctrine", "doctrine_migrations", "security", "swiftmailer", "twig", "web_profiler", "monolog", "debug", "maker", "web_server", "doctrine_fixtures", "mercure", "evo_log_viewer" in C:\Path\to\the\config\files\config/packages/evo_log_viewer.yaml (which is loaded in resource "C:\Path\to\the\config\files\config/packages/evo_log_viewer.yaml").`

I have configure the evo_log_viewer.yaml in the config/packages repo and evo_log_viewer_routes.yaml in the config/routes repo...

Do you have any idea ?

Hope I will use asap your project :D

EDIT : Fixed on your README.md

**Comment by GJoffrey** [comment]
Well, by commenting the evo_log_viewer.yaml it seems to work !

I'm interested to work with you on the front form if you want !

**Comment by evotodi** [comment]
There is a typo in the readme.
I just updated it. 
The config file should begin with evo_log_viewer:

```yaml
# List of log files to show
evo_log_viewer:
    log_files:
        # Unique identifier for the logfile
        somelog1:
            # Use full path
            path: 'Some/Full/Path/to/Log/File.Ext'

            # Pretty name to display else file name
            name: My Log Files Pretty Name 

            # (Optional) Number of days to pull from log. See ddtraceweb/monolog-parser.
            days: 0

            # (Optional) See ddtraceweb/monolog-parser for patterns.
            pattern: null

            # (Optional) PHP style date format of log file
            date_format: 'Y-m-d H:i:s'
            
            # (Optional) Log level spelling. Case sensitive
            levels:
                debug: DEBUG
                info: INFO
                notice: NOTICE
                warning: WARNING
                error: ERROR
                alert: ALERT
                critical: CRITICAL
                emergency: EMERGENCY

        somelog2:
            path: '/path/to/logfile.log'
            name: Pretty Logfile Name

    # Show App logs in var/log
    show_app_logs: true
```
